CREATE DATABASE Course
USE Course

CREATE TABLE Students
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL,
	Surname NVARCHAR(20),
	Point TINYINT
)

ALTER TABLE Students
ALTER COLUMN Surname NVARCHAR(20) NOT NULL

ALTER TABLE Students
ADD CONSTRAINT CK_Point CHECK(Point>=0 AND Point<=100)

ALTER TABLE Students
DROP CONSTRAINT CK_Point

ALTER TABLE Students
ADD DEFAULT 50 FOR Point

ALTER TABLE Students
ADD UNIQUE(Name)





DROP TABLE Students

INSERT INTO Students(Name,Surname)
VALUES
('NAME3','DSD')

DELETE FROM STUDENTS

SELECT * FROM Students